#!/usr/bin/php
<?php

include __DIR__."/lib/iceberg/autoloader/Autoloader.php";

use iceberg\config\Config;
use iceberg\command\Command;
use iceberg\autoloader\Autoloader;
use iceberg\errorhandler\ErrorHandler;

Autoloader::setNamespace("iceberg", __DIR__."/lib/iceberg");

ErrorHandler::register();

Config::loadFromFile(Config::TYPE_YAML, __DIR__."/config.yml");

Command::setNamespace("iceberg\(command)Command");
Command::load($argv);

echo PHP_EOL;